#!/bin/bash

# Check to see if nemesis-puppet package needs to be updated
yum clean expire-cache

# Check to see if any old gpg keys used to sign the repo needs to be deleted
for key in $(rpm -qa gpg-pubkey \* --qf "%{version}-%{release} %{summary}\n" |grep "Acquia Engineering <engineering@acquia.com>"); do
    /usr/bin/rpm -e --allmatches key >/dev/null 2>&1
done

# Update nemesis-puppet package if a new version is available
yum clean all && yum install -y nemesis-puppet

# Export all necessary environment variables
export RUBYLIB=/etc/puppet/lib:$RUBYLIB
export AMAZON_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')

# Run puppet
cd /etc/puppet && puppet apply manifests/nodes.pp --modulepath=/etc/puppet/modules:/etc/puppet/modules/third_party --logdest /var/log/puppet.log
