#!/bin/bash

# Check to see if nemesis-puppet package needs to be updated
yum clean expire-cache

# Check to see if any old gpg keys used to sign the repo needs to be deleted
for key in $(rpm -qa gpg-pubkey \* --qf "%{version}-%{release} %{summary}\n" |grep "Acquia Engineering <engineering@acquia.com>"); do
    /usr/bin/rpm -e --allmatches key >/dev/null 2>&1
done

# Install or update nemesis-puppet package if necessary
if [ $(yum list installed nemesis-puppet) == 0 ]; then
  yum update -y nemesis-puppet
else
  yum install -y nemesis-puppet
fi

# Export all necessary environment variables
export RUBYLIB=/etc/puppet/lib:$RUBYLIB
export AMAZON_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')

# Run puppet
cd /etc/puppet && puppet apply manifests/nodes.pp --logdest /var/log/puppet.log
