#!/usr/bin/env bash

# Copyright 2015 Acquia, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o nounset
set -o errexit

hash docker > /dev/null 2>&1 || {
  echo >&2 'Failed to locate docker binary'
  exit 1
}

# Try to connect to docker server
docker ps &>/dev/null

# Get list of volumes that can be cleaned
DOCKER_VOLUMES=$(docker volume ls -q -f "dangling=true")

if [ ! "$DOCKER_VOLUMES" == "" ]; then
  echo $DOCKER_VOLUMES | xargs -n 1 docker volume rm
else
  echo >&2 "Nothing to clean"
fi
