#!/bin/bash

# Check to see if nemesis-puppet package needs to be updated
apt-get update
VERSION_COUNT=$(apt-cache policy nemesis-puppet |  awk '/Installed|Candidate/{print $2}' | sort -u | wc -l)

if [ ${VERSION_COUNT} -ne 1 ]; then
  apt-get install -y nemesis-puppet
fi

# Run puppet
export RUBYLIB=/etc/puppet/lib:$RUBYLIB
# Find our region
export AMAZON_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')
cd /etc/puppet && puppet apply manifests/nodes.pp --logdest /var/log/puppet.log
