# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs/stdlib', '>= 4.5.1'

mod 'acquia/garethr-docker',
  :git => 'https://github.com/acquia/garethr-docker.git',
  :ref => '9686595978a1ace8dd98745a6e8389706bfe2724'

mod 'rodjek/logrotate',
  :git => 'https://github.com/rodjek/puppet-logrotate.git',
  :ref => '1.1.1'

mod 'deric/puppet-mesos',
  :git => 'https://github.com/deric/puppet-mesos.git',
  :ref => 'v0.6.4'

mod 'jfarrell/puppet-dnsmasq',
  :git => 'https://github.com/jfarrell/puppet-dnsmasq.git',
  :ref => '93958140cd293a5938aa020d7c383f92bfb86076'

mod 'saz/puppet-resolv_conf',
  :git => 'https://github.com/saz/puppet-resolv_conf.git',
  :ref => 'v3.0.5'