# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs/stdlib', '>= 4.5.1'

mod 'acquia/garethr-docker',
  :git => 'https://github.com/acquia/garethr-docker.git',
  :ref => '6dc10468ed14f6fcb41352c04953a08e8ef28bef'

mod 'rodjek/logrotate',
  :git => 'https://github.com/rodjek/puppet-logrotate.git',
  :ref => '1.1.1'

mod 'deric/puppet-mesos',
  :git => 'https://github.com/deric/puppet-mesos.git',
  :ref => 'v0.6.4'

mod 'acquia/puppet-aurora',
  :git => 'https://github.com/acquia/puppet-aurora.git',
  :ref => '0.10.x'
